version: "3.9"

services:
  user_management:
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app/src
    volumes:
      - ./user_management:/app
      - /app/__pycache__/
    ports:
      - "5001:5001"
    command: python src/UserController.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  product_catalog:
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app/src
    volumes:
      - ./product_catalog:/app
      - /app/__pycache__/
    ports:
      - "5002:5002"
    command: python src/ProductController.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
